### ISSUE TITLE
How the flatten operation worked?

### ISSUE THREAD

**Issue by panovr** [nihit/TensorFlow101#1]
I have a question about the 6-layer CNN Architecture in the writing: the last conv layer has 64 of 7x7 feature maps, through the flatten operation, these 64 of 7x7 feature maps are transformed into a 512 dimension hidden fc layer. I just wonder how this flatten operation did? Why the result fc layer is 512 dimension?
  Thanks!

**Comment by nihit** [comment]
The output of convolutional layers is a representation of the input in the space of features learned by the convolutional neural network. It is possible to flatten the output of the last convolutional layer and pass it directly to the output layer, but adding a fully-connected layer is usually done to learn non-linear combinations of these features.

The number of units in the full connected layer (512 in this case) is a hyperparameter that would need to be tuned.
